apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: bankzy-io-tls
spec:
  secretName: bankzy-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kbankzy.io
  dnsNames:
    - bankzy.io
    - www.bankzy.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - bankzy.io
          - www.bankzy.io
